# Generated by Django 5.2.9 on 2026-01-29 02:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('idperfil', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('fotoperfil', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('email_contacto', models.EmailField(blank=True, max_length=100, null=True)),
                ('descripcionperfil', models.CharField(max_length=300)),
                ('perfilactivo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('apellidos', models.CharField(max_length=60)),
                ('nombres', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('lugarnacimiento', models.CharField(max_length=60)),
                ('fechanacimiento', models.DateField()),
                ('numerocedula', models.CharField(max_length=10, unique=True)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('estadocivil', models.CharField(max_length=50)),
                ('licenciaconducir', models.CharField(blank=True, max_length=20, null=True)),
                ('telefonoconvencional', models.CharField(blank=True, max_length=10, null=True)),
                ('telefonofijo', models.CharField(blank=True, max_length=10, null=True)),
                ('direcciontrabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('direcciondomiciliaria', models.CharField(max_length=100)),
                ('sitioweb', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Datos Personales',
            },
        ),
        migrations.CreateModel(
            name='CursosRealizados',
            fields=[
                ('idcursorealizado', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('nombrecurso', models.CharField(max_length=250)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('totalhoras', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('descripcioncurso', models.TextField()),
                ('entidadpatrocinadora', models.CharField(max_length=150)),
                ('nombrecontactoauspicia', models.CharField(max_length=200)),
                ('telefonocontactoauspicia', models.CharField(max_length=60)),
                ('emailempresapatrocinadora', models.EmailField(max_length=150)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.FileField(blank=True, null=True, upload_to='certificados/cursos/')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Perfil.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('idexperiencilaboral', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('cargodesempenado', models.CharField(max_length=200)),
                ('nombrempresa', models.CharField(max_length=150)),
                ('lugarempresa', models.CharField(max_length=150)),
                ('emailempresa', models.EmailField(max_length=200)),
                ('sitiowebempresa', models.URLField(blank=True, max_length=500, null=True)),
                ('nombrecontactoempresarial', models.CharField(max_length=200)),
                ('telefonocontactoempresarial', models.CharField(max_length=100)),
                ('fechainiciogestion', models.DateField()),
                ('fechafingestion', models.DateField(blank=True, null=True)),
                ('descripcionfunciones', models.TextField()),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.FileField(blank=True, null=True, upload_to='certificados/experiencia/')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Perfil.datospersonales')),
            ],
            options={
                'ordering': ['-fechainiciogestion'],
            },
        ),
        migrations.CreateModel(
            name='ProductosAcademicos',
            fields=[
                ('idproductoacademico', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('nombrerecurso', models.CharField(max_length=200)),
                ('clasificador', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Perfil.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosLaborales',
            fields=[
                ('idproductoslaborales', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('nombreproducto', models.CharField(max_length=100)),
                ('fechaproducto', models.DateField()),
                ('descripcion', models.TextField()),
                ('url_proyecto', models.URLField(blank=True, max_length=500, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Perfil.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='Reconocimientos',
            fields=[
                ('idreconocimiento', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('tiporeconocimiento', models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=200)),
                ('fechareconocimiento', models.DateField()),
                ('descripcionreconocimiento', models.TextField()),
                ('entidadpatrocinadora', models.CharField(max_length=300)),
                ('nombrecontactoauspicia', models.CharField(max_length=300)),
                ('telefonocontactoauspicia', models.CharField(max_length=100)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.FileField(blank=True, null=True, upload_to='reconocimientos/')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Perfil.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('idventagarage', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('nombreproducto', models.CharField(max_length=100)),
                ('estadoproducto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40)),
                ('foto_producto', models.ImageField(blank=True, null=True, upload_to='garage/fotos/', verbose_name='Foto para la Web')),
                ('documento_interes', models.FileField(blank=True, null=True, upload_to='garage/documentos/', verbose_name='PDF solo para el CV')),
                ('descripcion', models.TextField()),
                ('valordelbien', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Perfil.datospersonales')),
            ],
        ),
    ]
