# Generated by Django 5.2.9 on 2026-01-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosacademicos',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='academicos/', verbose_name='Imagen Representativa'),
        ),
    ]
