# Generated by Django 5.2.9 on 2026-01-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0002_productosacademicos_imagen_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='rutacertificado',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='certificados/cursos/'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fotoperfil',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='perfil/'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='certificados/experiencia/'),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='imagen_producto',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='academicos/', verbose_name='Imagen Representativa'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='rutacertificado',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='reconocimientos/'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='documento_interes',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='garage/documentos/', verbose_name='PDF solo para el CV'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='foto_producto',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='garage/fotos/', verbose_name='Foto para la Web'),
        ),
    ]
